name: recognize-ci

on:
  push:
    branches:
      - main
#    tags:
#      - 'v.*'

jobs:
  build:
    runs-on: windows-latest 
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      PIPENV_VENV_IN_PROJECT: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v4
#      with:
#        fetch-depth: 0

    - name: Print Config
      run: |
        echo "GITHUB_REPOSITORY=$env:GITHUB_REPOSITORY"
        echo "GITHUB_EVENT_NAME=$env:GITHUB_EVENT_NAME"
        echo "GITHUB_REF=$env:GITHUB_REF"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.x

    # Install the .NET Core workload
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    - name: conv utf-8
      run: |
        Get-Content -Encoding Shift_JIS src\py-recognition\build.ps1 | Set-Content src\py-recognition\build.ps1.new
        rm src\py-recognition\build.ps1
        Move-Item src\py-recognition\build.ps1.new src\py-recognition\build.ps1

    - name: Build CLI app
      run: |
        pushd src\py-recognition
        pip install pipenv
        python -m pipenv install --dev
        # todo: ブートローダーを差し替える
        python -m pipenv run archive1
        copy .\c\mm-interop.dll .\dist\recognize\
        popd

    - name: Build GUI app
      run: |
        pushd src\cs-recognition-frontend
        .\build.bat
        popd

    - name: Create Artifact Directory
      run: |
        mkdir recognize\src\py-recognition
        move src\cs-recognition-frontend\recognize-gui.exe recognize
        move src\py-recognition\dist recognize\src\py-recognition

    - name: Create Artifact Zip
      run: Compress-Archive -Path recognize -DestinationPath "recognize.zip"

    - name: Split Artifact Zip
      run: $cnt = 0; Get-Content recognize.zip -Encoding Byte -ReadCount 1800mb | % {$_ | Set-Content "recognize-${{github.ref_name}}.zip.{{$cnt}}" -Encoding Byte; $cnt++}
