name: recognize-ci

on:
  push:
    branches:
      - main
#    tags:
#      - 'v.*'

jobs:
  build:
    runs-on: windows-latest 
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v4
#      with:
#        fetch-depth: 0

    - name: Print Config
      run: |
        echo "GITHUB_REPOSITORY=$env:GITHUB_REPOSITORY"
        echo "GITHUB_EVENT_NAME=$env:GITHUB_EVENT_NAME"
        echo "GITHUB_REF=$env:GITHUB_REF"

    # Install the .NET Core workload
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    - name: fix lf
      run: |
        # 試しに入れる
        ls -r -file -filter *.ps1 | % { (get-content -encoding Default $_.FullName) -join "`r`n" | set-content -encoding Default $_.FullName }

    - name: Build app
      run: .\build-all.bat
      shell: cmd

    - name: Create Artifact Directory
      run: |
        mkdir recognize\src\py-recognition
        move recognize-gui.exe recognize
        move src\py-recognition\dist recognize\src\py-recognition

    - name: Create Artifact Zip
      run: Compress-Archive -Path recognize -DestinationPath "recognize-${{github.ref_name}}.zip"
